#Runs all the tests! Triggers on push and PR for quick feedback.
#Tests are not very comprehensive right now, so don't put too much faith in this.
name: run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Execute tests
        run: PACKER_ACC=1 go test -count 1 -v $(go list ./...) -timeout=120m